name: viztutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=2.2.2
  - asn1crypto=0.24.0
  - backcall=0.1.0
  - boost-cpp=1.67.0
  - branca=0.3.0
  - bzip2=1.0.6
  - ca-certificates=2018.8.24
  - cairo=1.14.12
  - cartopy=0.16.0
  - certifi=2018.8.24
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - click-plugins=1.0.3
  - cligj=0.4.0
  - cryptography=2.3.1
  - cryptography-vectors=2.3.1
  - curl=7.61.0
  - cycler=0.10.0
  - dbus=1.13.0
  - decorator=4.3.0
  - descartes=1.1.0
  - entrypoints=0.2.3
  - expat=2.2.5
  - fiona=1.7.13
  - folium=0.6.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - gdal=2.2.4
  - geopandas=0.4.0
  - geos=3.6.2
  - geotiff=1.4.2
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.55.0
  - gst-plugins-base=1.12.5
  - gstreamer=1.12.5
  - hdf4=4.2.13
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.7
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9c
  - json-c=0.12.1
  - jsonschema=2.6.0
  - kealib=1.4.9
  - kiwisolver=1.0.1
  - krb5=1.14.6
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgdal=2.2.4
  - libgfortran=3.0.0
  - libgfortran-ng=7.2.0
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.35
  - libpq=9.6.3
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libstdcxx-ng=7.2.0
  - libtiff=4.0.9
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lxml=4.2.4
  - markupsafe=1.0
  - matplotlib=2.2.3
  - munch=2.3.2
  - ncurses=6.1
  - olefile=0.45.1
  - openjpeg=2.3.0
  - openssl=1.0.2p
  - owslib=0.16.0
  - pandas=0.23.4
  - parso=0.3.1
  - pcre=8.41
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pillow=5.2.0
  - pip=18.0
  - pixman=0.34.0
  - poppler=0.61.1
  - poppler-data=0.4.9
  - proj4=4.9.3
  - prompt_toolkit=1.0.15
  - psycopg2=2.7.5
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.18
  - pyepsg=0.3.2
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyproj=1.9.5.1
  - pyqt=5.6.0
  - pysal=1.14.4.post2
  - pyshp=1.2.12
  - pysocks=1.6.8
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - qt=5.6.2
  - readline=7.0
  - requests=2.19.1
  - rtree=0.8.3
  - setuptools=40.2.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.11.0
  - sqlalchemy=1.2.11
  - sqlite=3.24.0
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1
  - traitlets=4.3.2
  - typing=3.6.4
  - urllib3=1.23
  - vincent=0.4.4
  - wcwidth=0.1.7
  - wheel=0.31.1
  - xerces-c=3.2.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.2
  - xorg-libx11=1.6.6
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xorg-libxext=1.3.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zlib=1.2.11
  - intel-openmp=2018.0.3
  - libopenblas=0.2.20
  - mkl=2018.0.3
  - numpy=1.14.3
  - numpy-base=1.14.3
  - scipy=0.19.1
